version: '3.8'

services:
  client:
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096 --expose-gc
      - NODE_ENV=development
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 4g
    memswap_limit: 4g
    cpu_shares: 1024
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s