const tables = [
  'admin_users',
  'application',
  'article_categories',
  'article_category_relations',
  'article_tag_relations',
  'article_tags',
  'articles',
  'blocked_companies',
  'candidates',
  'career_status_entries',
  'company_accounts',
  'company_groups',
  'company_notification_settings',
  'company_user_group_permissions',
  'company_users',
  'custom_industries',
  'decline_reasons',
  'education',
  'email_verification_codes',
  'expectations',
  'favorites',
  'hidden_candidates',
  'job_postings',
  'job_type_experience',
  'message_templates',
  'messages',
  'ng_keywords',
  'notice_categories',
  'notice_category_relations',
  'notices',
  'notification_settings',
  'password_reset_tokens',
  'rooms',
  'saved_candidates',
  'scout_sends',
  'scout_settings',
  'search_history',
  'search_templates',
  'selection_progress',
  'signup_progress',
  'signup_verification_codes',
  'skills',
  'unread_notifications',
  'withdrawn_candidates',
  'work_experience',
];

console.log('Table search patterns:');
tables.forEach(table => {
  console.log(
    `rg "\\.from\\(['\"]${table}['\"]\\)" . --type-add 'source:*.{ts,tsx,js,jsx}' -t source`
  );
});
