import type { JobType, JobTypeGroup } from '@/types';

export const JOB_TYPE_GROUPS: JobTypeGroup[] = [
  {
    id: 'consultant',
    name: 'コンサルタント',
    jobTypes: [
      { id: 'strategy', name: '戦略系' },
      { id: 'general', name: '総合系' },
      { id: 'finance', name: '財務系' },
      { id: 'restructuring', name: '再生系' },
      { id: 'organization', name: '組織系' },
      { id: 'management', name: '経営コンサルタント' },
      { id: 'venture', name: 'ベンチャーコンサルタント' },
      { id: 'business', name: 'ビジネスコンサルタント' },
    ],
  },
  {
    id: 'it-consultant',
    name: 'ITコンサルタント',
    jobTypes: [
      { id: 'it-strategy', name: 'IT戦略コンサルタント' },
      { id: 'erp', name: 'ERPコンサルタント' },
      { id: 'crm', name: 'CRMコンサルタント' },
      { id: 'scm', name: 'SCMコンサルタント' },
      { id: 'pmo', name: 'PMOコンサルタント' },
      { id: 'sap', name: 'SAPコンサルタント' },
      { id: 'web', name: 'Webコンサルタント' },
      { id: 'security', name: 'セキュリティコンサルタント' },
    ],
  },
  {
    id: 'project-manager',
    name: 'プロジェクトマネージャー',
    jobTypes: [
      { id: 'pm-general', name: 'プロジェクトマネージャー' },
      { id: 'pmo-general', name: 'PMO' },
      { id: 'pm-web', name: 'Webプロジェクトマネージャー' },
      { id: 'pm-system', name: 'システムプロジェクトマネージャー' },
      { id: 'pm-infra', name: 'インフラプロジェクトマネージャー' },
    ],
  },
  {
    id: 'product-manager',
    name: 'プロダクトマネージャー',
    jobTypes: [
      { id: 'product-manager', name: 'プロダクトマネージャー' },
      { id: 'product-owner', name: 'プロダクトオーナー' },
      { id: 'service-planner', name: 'サービス企画' },
      { id: 'product-marketing', name: 'プロダクトマーケティング' },
    ],
  },
  {
    id: 'engineer',
    name: 'システムエンジニア',
    jobTypes: [
      { id: 'se-general', name: 'システムエンジニア' },
      { id: 'web-engineer', name: 'Webエンジニア' },
      { id: 'app-engineer', name: 'アプリケーションエンジニア' },
      { id: 'infra-engineer', name: 'インフラエンジニア' },
      { id: 'network-engineer', name: 'ネットワークエンジニア' },
      { id: 'database-engineer', name: 'データベースエンジニア' },
      { id: 'security-engineer', name: 'セキュリティエンジニア' },
      { id: 'ai-engineer', name: 'AIエンジニア' },
      { id: 'data-scientist', name: 'データサイエンティスト' },
      { id: 'frontend-engineer', name: 'フロントエンドエンジニア' },
      { id: 'backend-engineer', name: 'バックエンドエンジニア' },
      { id: 'fullstack-engineer', name: 'フルスタックエンジニア' },
    ],
  },
  {
    id: 'sales-bd',
    name: '営業・事業開発',
    jobTypes: [
      { id: 'sales', name: '営業' },
      { id: 'inside-sales', name: 'インサイドセールス' },
      { id: 'field-sales', name: 'フィールドセールス' },
      { id: 'customer-success', name: 'カスタマーサクセス' },
      { id: 'business-development', name: '事業開発' },
      { id: 'alliance', name: 'アライアンス' },
      { id: 'sales-planning', name: '営業企画' },
    ],
  },
  {
    id: 'backoffice',
    name: 'バックオフィス',
    jobTypes: [
      { id: 'hr', name: '人事' },
      { id: 'recruiting', name: '採用' },
      { id: 'labor', name: '労務' },
      { id: 'general-affairs', name: '総務' },
      { id: 'legal', name: '法務' },
      { id: 'accounting', name: '経理' },
      { id: 'finance', name: '財務' },
      { id: 'internal-audit', name: '内部監査' },
      { id: 'corporate-planning', name: '経営企画' },
      { id: 'pr', name: '広報' },
      { id: 'ir', name: 'IR' },
    ],
  },
  {
    id: 'other',
    name: 'その他',
    jobTypes: [
      { id: 'marketing', name: 'マーケティング' },
      { id: 'designer', name: 'デザイナー' },
      { id: 'writer', name: 'ライター' },
      { id: 'director', name: 'ディレクター' },
      { id: 'producer', name: 'プロデューサー' },
      { id: 'analyst', name: 'アナリスト' },
      { id: 'researcher', name: 'リサーチャー' },
      { id: 'other', name: 'その他' },
    ],
  },
];
