export const ENGLISH_LEVELS = [
  { value: '', label: 'レベルを選択' },
  { value: 'ネイティブ', label: 'ネイティブ' },
  { value: 'ビジネスレベル', label: 'ビジネスレベル' },
  { value: '日常会話', label: '日常会話' },
  { value: '基礎会話', label: '基礎会話' },
  { value: 'なし', label: 'なし' },
];

export const LANGUAGE_OPTIONS = [
  { value: '', label: '言語を選択' },
  { value: 'インドネシア語', label: 'インドネシア語' },
  { value: 'イタリア語', label: 'イタリア語' },
  { value: 'スペイン語', label: 'スペイン語' },
  { value: 'タイ語', label: 'タイ語' },
  { value: 'ドイツ語', label: 'ドイツ語' },
  { value: 'フランス語', label: 'フランス語' },
  { value: 'ポルトガル語', label: 'ポルトガル語' },
  { value: 'マレー語', label: 'マレー語' },
  { value: 'ロシア語', label: 'ロシア語' },
  { value: '韓国語', label: '韓国語' },
  { value: '中国語（簡体字）', label: '中国語（簡体字）' },
  { value: '中国語（繁体字）', label: '中国語（繁体字）' },
  { value: 'ベトナム語', label: 'ベトナム語' },
  { value: 'アラビア語', label: 'アラビア語' },
  { value: 'ヒンディー語', label: 'ヒンディー語' },
  { value: 'オランダ語', label: 'オランダ語' },
  { value: 'スウェーデン語', label: 'スウェーデン語' },
  { value: 'ポーランド語', label: 'ポーランド語' },
  { value: 'トルコ語', label: 'トルコ語' },
  { value: '日本語', label: '日本語' },
  { value: 'ベンガル語', label: 'ベンガル語' },
  { value: 'タガログ語', label: 'タガログ語' },
  { value: 'タミル語', label: 'タミル語' },
  { value: 'ミャンマー語', label: 'ミャンマー語' },
];

export const SALARY_OPTIONS = [
  { value: '300', label: '300万円' },
  { value: '400', label: '400万円' },
  { value: '500', label: '500万円' },
  { value: '600', label: '600万円' },
  { value: '700', label: '700万円' },
  { value: '800', label: '800万円' },
  { value: '900', label: '900万円' },
  { value: '1000', label: '1000万円' },
  { value: '1200', label: '1200万円' },
  { value: '1500', label: '1500万円' },
  { value: '2000', label: '2000万円以上' },
];
